spring.application.name=jwtAuthentification

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/jwtdb
spring.datasource.username=jbw
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#configuration du jwt
app.secret-key=22355eet6746fhj86uhi096ugj6765545#$hfjukko9j
#definition de la date d'expiration du jwt
app.expiration-time=900000